version: "3.7"

services:

    nestjs:
        container_name: nestjs
        build: 
            context: .
            dockerfile: Dockerfile
        command: yarn run start:dev
        volumes : 
            - .:/usr/src/app
        ports:
        - 3000:3000
        environment: 
            HTTP_PORT: 3000
        depends_on:
        - kafka

    zookeeper:
        container_name: zookeeper
        image: bitnami/zookeeper:3.6.1
        ports:
        - 2181:2181
        volumes:
        - zookeeper_volume:/bitnami
        environment:
        - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        container_name: kafka
        image: bitnami/kafka:2.6.0
        ports:
        - 9092:9092
        volumes:
        - kafka_volume:/bitnami
        environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
        - zookeeper


volumes:
    kafka_volume:
        driver: local
    zookeeper_volume:
        driver: local